version: 2

refs:
  - &container
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
  - &docker_setup
    setup_remote_docker:
      docker_layer_caching: true
  - &restore_cache
    restore_cache:
      keys:
        - v1-dependencies-{{ checksum "yarn.lock" }}
        - v1-dependencies-
  - &save_cache
    save_cache:
      paths:
        - node_modules
      key: v1-dependencies-{{ checksum "yarn.lock" }}
  - &yarn_install
    run:
      name: Yarn Install
      command: yarn --frozen-lockfile
  - &test
    run:
      name: Test
      command:
        (docker pull mongo:3.6.10-stretch & docker pull mongo:4.1.7-xenial) &&
        (docker run --detach -p 27023:27017 --env MONGO_INITDB_DATABASE=database mongo:3.6.10-stretch & docker run --detach -p 27024:27017 --env MONGO_INITDB_DATABASE=database mongo:4.1.7-xenial) &&
        docker build -t then-mongo-test . && docker run then-mongo-test

jobs:
  all:
    <<: *container
    steps:
      - checkout
      - *restore_cache
      - *yarn_install
      - *save_cache
      - *docker_setup
      - *test

  master:
    <<: *container
    steps:
      - checkout
      - *restore_cache
      - *yarn_install
      - *save_cache
      - *docker_setup
      - *test

workflows:
  version: 2
  all:
    jobs:
      - all:
          filters:
            branches:
              ignore:
                - master
  master:
    jobs:
      - master:
          filters:
            branches:
              only: master
  nightly:
    triggers:
      - schedule:
          cron: '0 1 * * *'
          filters:
            branches:
              only: master
    jobs:
      - all:
          filters:
            branches:
              only: master
